// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'firebase_options.dart';


// ...
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtgJ0Qq05wf0dCKO9U0IjRhMYkvEREZpc',
    appId: '1:512358689598:web:7609c27730d5398f7c5a6f',
    messagingSenderId: '512358689598',
    projectId: 'womansafety-1c691',
    authDomain: 'womansafety-1c691.firebaseapp.com',
    databaseURL: 'https://womansafety-1c691-default-rtdb.firebaseio.com',
    storageBucket: 'womansafety-1c691.appspot.com',
    measurementId: 'G-3PBZP0E9KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASQelJi5rlCddnobaBOwTcGW226pjBqck',
    appId: '1:512358689598:android:7f935fb5db6bbb097c5a6f',
    messagingSenderId: '512358689598',
    projectId: 'womansafety-1c691',
    databaseURL: 'https://womansafety-1c691-default-rtdb.firebaseio.com',
    storageBucket: 'womansafety-1c691.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkcwHZUYpIy6porZqz7V2BII9rHsfw8lQ',
    appId: '1:512358689598:ios:e4d36456602cd3667c5a6f',
    messagingSenderId: '512358689598',
    projectId: 'womansafety-1c691',
    databaseURL: 'https://womansafety-1c691-default-rtdb.firebaseio.com',
    storageBucket: 'womansafety-1c691.appspot.com',
    iosBundleId: 'com.example.therakshalink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkcwHZUYpIy6porZqz7V2BII9rHsfw8lQ',
    appId: '1:512358689598:ios:e4d36456602cd3667c5a6f',
    messagingSenderId: '512358689598',
    projectId: 'womansafety-1c691',
    databaseURL: 'https://womansafety-1c691-default-rtdb.firebaseio.com',
    storageBucket: 'womansafety-1c691.appspot.com',
    iosBundleId: 'com.example.therakshalink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtgJ0Qq05wf0dCKO9U0IjRhMYkvEREZpc',
    appId: '1:512358689598:web:322343d04e3805917c5a6f',
    messagingSenderId: '512358689598',
    projectId: 'womansafety-1c691',
    authDomain: 'womansafety-1c691.firebaseapp.com',
    databaseURL: 'https://womansafety-1c691-default-rtdb.firebaseio.com',
    storageBucket: 'womansafety-1c691.appspot.com',
    measurementId: 'G-K8D9HP88CB',
  );
}
